### ISSUE TITLE
Need to update content.js to match the new  Docsend HTML format

### ISSUE THREAD

**Issue by ramyadeeb** [mdp/SlidePrint#1]
Basically  need to make this change (wasn't sure I could edit the file)

diff DocsendPrint-master/content.js DocsendPrint-1.0.0/content.js
4c4
<   return document.querySelectorAll(".viewer_content-container img.page-view");
---
>   return document.querySelectorAll("#viewer img.page-view");

**Comment by ramyadeeb** [comment]
So sorry Mark. You had already fixed it last year

https://github.com/mdp/DocsendPrint/commit/1b9a7cc2034c7208add3282bb33097bc190f9027

#1b9a7cc2034c7208add3282bb33097bc190f9027

So we actually need to undo the change. Mea culpa

**Comment by mdp** [comment]
Oh, sorry, I misread your change. Yeah, it's back in there. I haven't reinstalled in on my new machine, so I haven't tested it lately.
