### ISSUE TITLE
Add pitch.com

### ISSUE THREAD

**Issue by renvcf** [mdp/SlidePrint#16]
Love the addin.  Pitch.com seems to be the new tool everyone is using.  Can we add that to SlidePrint?

**Comment by mdp** [comment]
Yep, let me take a stab at it this week. I agree, it's the hot new docsend.

**Comment by mdp** [comment]
Ah, looks like I already had this in development and just needed to push it out with a small change. Will in in the store shortly and I'll update this issue when it's out.

**Comment by mdp** [comment]
This is live in v2.3.1 of the extension. Thanks!

**Comment by renvcf** [comment]
Can confirm it works as expected.  Love it.
